name: markdown slides
on: [push]
jobs:
  github release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - uses: actions/setup-node@master
      with:
        node-version: 13.x
    - name: Variables
      run: |
        echo "::set-env name=GITHUB_REPOSITORY_USER::$(dirname $GITHUB_REPOSITORY)"
        echo "::set-env name=GITHUB_REPOSITORY_NAME::$(basename $GITHUB_REPOSITORY)"
        echo "::set-env name=GITHUB_PAGES_CANONICAL::https://${GITHUB_REPOSITORY_USER}.github.io/${GITHUB_REPOSITORY_NAME}/"
    - name: Build pptx
      run: |
        npx @marp-team/marp-cli pitchme.md --pptx --output ${{ github.sha }}.pptx
    - name: Build pdf
      run: |
        npx @marp-team/marp-cli pitchme.md --pdf --output ${{ github.sha }}.pdf

    # - name: Build image
    #   run: |
    #     npx @marp-team/marp-cli pitchme.md --output ${{ github.sha }}.png --image png
    # - name: Build html
    #   run: |
    #     npx @marp-team/marp-cli pitchme.md --output index.html --og-image "${GITHUB_PAGES_CANONICAL}thumbnail.png" --url "${GITHUB_PAGES_CANONICAL}"

    - name: Save
      uses: actions/upload-artifact@v1
      with:
        name: ${{ join( 'PowerPoint Open XML Presentation v',  github.run_number) }}
        path: ${{ github.sha }}.pptx

    - name: Save
      uses: actions/upload-artifact@v1
      with:
        name: ${{ join( 'Portable Document Format v',  github.run_number) }}
        path: ${{ github.sha }}.pdf
